{
 "title": "pocket metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "pocket-lt-1,pocket-lt-2,pocket-de-1,pocket"
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Relays per Chain",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pocketcore_service_relay_count_for_0001{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for pocket"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0004{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for bsc"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0005{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for fuse"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0006{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for solana"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0009{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for polygon"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0021{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for eth-mainnet"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0022{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for eth-archive"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0023{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for ropsten"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0025{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for rinkeby"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0026{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for goerli"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0027{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for xdai"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0028{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for eth-arch-trace"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0040{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for harmony"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0049{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "relays for harmony"
    }
   ]
  },
  {
   "title": "Error count all Chains",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(pocketcore_service_err_count_for_all{job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Avg relay time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0001_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time pocket"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0004_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time bsc"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0005_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time fuse"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0006_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time solana"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0009_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time polygon"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0021_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time eth-mainnet"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0022_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time eth-archival"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0023_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time ropsten"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0025_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time rinkeby"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0026_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time goerli"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0027_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time xdai"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0028_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time eth-archival-trace"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0040_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time harmony"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0049_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "relay time fantom"
    }
   ]
  },
  {
   "title": "Session count per Chain Both nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0001{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "pocket"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0005{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "fuse"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0021{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "eth-mainnet"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0022{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "eth-archive"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0023{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "eth-ropsten"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0025{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "eth-rinkeby"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0026{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "eth-goerli"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0027{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "xdai"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0028{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "eth-archive-trace"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0040{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "harmony"
    }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "latest_block_height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "missing_validators",
   "type": "gauge",
   "description": "consensus_missing_validators",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "mempool tx size",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tendermint_mempool_tx_size_bytes_bucket{job=~\"$job\"}[1m])))"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=~\"$job\"}",
     "legendFormat": "Peers {{ job }}"
    }
   ]
  },
  {
   "title": "consensus_validators_power",
   "type": "gauge",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Block Processing Time  ",
   "type": "status-history",
   "description": "Block Processing Time sum / count",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "tendermint_state_block_processing_time_sum{job=~\"$job\"} / 60000",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "block interval",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Avg relay time for all chains",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_all_bucket{job=~\"$job\"}[1m])))",
     "legendFormat": "avg relay all bucket"
    }
   ]
  },
  {
   "title": "p2p_peer_send_bytes",
   "type": "timeseries",
   "description": "number of bytes per channel sent to a given peer",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(tendermint_p2p_peer_send_bytes_total{job=~\"$job\"}[1m])",
     "legendFormat": "Peer {{ peer_id }}"
    }
   ]
  }
 ]
}